spring.application.name=RepuestosAutomotriz Final proyect
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/DBStoreMech?createDatabaseIfNotExist=true&useSSL=false
?createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=quintom
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true